import { Playfair_Display} from "next/font/google";
import "./globals.css";
import Provider from "./components/Provider";
import DarkModeContextProvider from "@/context/DarkMode";

const playfair = Playfair_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <Provider>
          <DarkModeContextProvider>
            {children}
          </DarkModeContextProvider>
        </Provider>
      </body>
    </html>
  );
}
